### ISSUE TITLE
Support JSON based models in salesforce connector

### ISSUE THREAD

**Issue by chirino** [syndesisio/connectors#54]

**Comment by dhirajsb** [comment]
I have added support for generating JSON payloads and generating schema models upstream for [CAMEL-10744](https://issues.apache.org/jira/browse/CAMEL-10744) and [CAMEL-10743](https://issues.apache.org/jira/browse/CAMEL-10743). 

To generate a JSON schema, use the [JsonUtils. getSObjectJsonSchema](https://github.com/apache/camel/blob/master/components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/utils/JsonUtils.java#L109) utility API in the component to convert an `SObjectDescription` which can be retrieved using the [getDescription](https://github.com/apache/camel/blob/master/components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/RestApiIntegrationTest.java#L530-L531) REST endpoint. 

Use the [rawPayload=true](https://github.com/apache/camel/blob/master/components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/RestApiIntegrationTest.java#L530-L531) endpoint option in Syndesis applications to send and receive raw JSON or XML Strings instead of having to generate DTOs. 

I am not familiar with Syndesis connectors to add this directly as an operation, but the implementation should be simple enough for someone familiar with them. Or, let me know if you need me to work on the connector as well to add this as an operation.

**Comment by dhirajsb** [comment]
@chirino or @rhuss can you close this issue? I don't have rights to assign issues to myself or close them.
