### ISSUE TITLE
Unrecognized field "optionalPrefix"

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/connectors#57]
Caused by: io.syndesis.core.SyndesisServerException: An error has occurred.
	at io.syndesis.dao.DataManagerTest.setup(DataManagerTest.java:47)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: 
Unrecognized field "optionalPrefix" (class io.syndesis.model.connection.ConfigurationProperty$Builder), not marked as ignorable (12 known properties: "secret", "componentProperty", "deprecated", "kind", "type", "javaType", "displayName", "group", "defaultValue", "label", "description", "required"])

Should get removed from the twitter-search schema.

**Comment by davsclaus** [comment]
The `optionalPrefix` is a known attribute in the Camel component json schema. Syndesis should learn how to handle it, or ignore it.

For example
```
 "useFixedDelay": { "kind": "parameter", "displayName": "Use Fixed Delay", "group": "scheduler", "label": "consumer,scheduler", "type": "boolean", "javaType": "boolean", "optionalPrefix": "consumer.", "deprecated": false, "secret": false, "defaultValue": true, "description": "Controls if fixed delay or fixed rate is used. See ScheduledExecutorService in JDK for details." },
```
Here there is 
```
"optionalPrefix": "consumer."
```

which means that the Camel endpoint uri option can be specified with an option prefix if desired (its mainly due to backwards compatiblity in Camel where some options could be specified in two ways).

So you can say with the optional prefix:
```
...?consumer.useFixedDelay=true
```
or without the optional prefix (most commonly used)
```
...?.useFixedDelay=true
```

**Comment by davsclaus** [comment]
Because syndesis is in control of Camel, then you can basically ignore the `optionalPrefix` attribute and just specify the options as today without this prefix.

**Comment by KurtStam** [comment]
Makes sense. Thx @davsclaus
